#!/bin/sh

set -eu

# ==============================================================================
# image.sh
#
# Build and push the Diaries responder container image using daemonless BuildKit.
#
# The script:
#   - locates the Diaries responder and project directories;
#   - loads the build metadata generated by the earlier build stage;
#   - validates the required environment and external commands;
#   - resolves the image repository and tags;
#   - creates an isolated temporary Docker authentication configuration;
#   - builds and pushes the image;
#   - writes imageinfo for later pipeline stages.
#
# Shell tracing is deliberately not enabled because this script handles Docker
# registry credentials.
# ==============================================================================


# ------------------------------------------------------------------------------
# Small logging/error helpers.
# ------------------------------------------------------------------------------

log() {
    printf '%s\n' "$*"
}

die() {
    log "ERROR: $*" >&2
    exit 1
}


# ------------------------------------------------------------------------------
# Locate the responder and top-level Diaries project directories.
#
# This script is located under:
#
#     diaries-responder/scripts
#
# Moving up one level gives the responder directory and another level gives the
# top-level Diaries project directory.
# ------------------------------------------------------------------------------

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd) \
    || die "Could not determine the script directory."

SUBPROJECT_DIR=$(dirname -- "${SCRIPT_DIR}")
PROJECT_DIR=$(dirname -- "${SUBPROJECT_DIR}")
BUILD_DIR="${SUBPROJECT_DIR}/build"
BUILD_INFO_FILE="${BUILD_DIR}/buildinfo"
IMAGE_INFO_FILE="${BUILD_DIR}/imageinfo"


# ------------------------------------------------------------------------------
# Validate and load the build metadata generated by the earlier build stage.
# ------------------------------------------------------------------------------

[ -f "${BUILD_INFO_FILE}" ] \
    || die "Build information file not found: ${BUILD_INFO_FILE}"

# shellcheck disable=SC1090
. "${BUILD_INFO_FILE}"


# ------------------------------------------------------------------------------
# Validate the required environment variables.
#
# REPOSITORY and VERSION normally come from buildinfo. Registry credentials and
# image naming values are supplied by the CI environment.
# ------------------------------------------------------------------------------

required_vars='
REPOSITORY
VERSION
IMAGE_REGISTRY
IMAGE_NAME
DOCKER_USERNAME
DOCKER_PASSWORD
'

for var in ${required_vars}; do
    eval "value=\${${var}-}"
    if [ -z "${value}" ]; then
        die "${var} is not set or empty."
    fi
done


# ------------------------------------------------------------------------------
# Validate the external commands required by this script.
# ------------------------------------------------------------------------------

for command_name in buildctl-daemonless.sh base64 mktemp date; do
    command -v "${command_name}" >/dev/null 2>&1 \
        || die "Required command not found on PATH: ${command_name}"
done


# ------------------------------------------------------------------------------
# Define and validate the Dockerfile used to build the responder image.
# ------------------------------------------------------------------------------

DOCKERFILE_DIR="${SUBPROJECT_DIR}/scripts/files"
DOCKERFILE_PATH="${DOCKERFILE_DIR}/Dockerfile"

[ -f "${DOCKERFILE_PATH}" ] \
    || die "Dockerfile not found: ${DOCKERFILE_PATH}"


# ------------------------------------------------------------------------------
# Resolve the image repository and tags.
#
# A repository-specific convenience tag is published in addition to VERSION:
#
#   releases    -> latest
#   integration -> integration
#   snapshots   -> snapshot
# ------------------------------------------------------------------------------

if [ -n "${IMAGE_NAMESPACE:-}" ]; then
    IMAGE_REPO="${IMAGE_REGISTRY}/${IMAGE_NAMESPACE}/${IMAGE_NAME}"
else
    IMAGE_REPO="${IMAGE_REGISTRY}/${IMAGE_NAME}"
fi

IMAGE_TAG="${VERSION}"

EXTRA_TAGS=""
case "${REPOSITORY}" in
    releases)
        EXTRA_TAGS="latest"
        ;;
    integration)
        EXTRA_TAGS="integration"
        ;;
    snapshots)
        EXTRA_TAGS="snapshot"
        ;;
esac

NAMES="${IMAGE_REPO}:${IMAGE_TAG}"
for tag in ${EXTRA_TAGS}; do
    NAMES="${NAMES},${IMAGE_REPO}:${tag}"
done

log "PROJECT_DIR=${PROJECT_DIR}"
log "BUILD_DIR=${BUILD_DIR}"
log "VERSION=${VERSION}"
log "REPOSITORY=${REPOSITORY}"
log "IMAGE_REPO=${IMAGE_REPO}"
log "IMAGE_TAG=${IMAGE_TAG}"
log "NAMES=${NAMES}"


# ------------------------------------------------------------------------------
# Warn if the responder build output is not present.
#
# This is not currently fatal because the Dockerfile/build pipeline determines
# exactly which generated artifacts are required.
# ------------------------------------------------------------------------------

if [ ! -d "${SUBPROJECT_DIR}/build/libs" ]; then
    log "WARNING: Responder build output directory not found: ${SUBPROJECT_DIR}/build/libs" >&2
    log "If the Dockerfile depends on the packaged responder JAR, run the build stage first." >&2
fi


# ------------------------------------------------------------------------------
# Create an isolated Docker authentication configuration for BuildKit.
#
# Do not write to ${HOME}/.docker/config.json. Using a temporary DOCKER_CONFIG
# directory prevents this build from overwriting or deleting an existing Docker
# login belonging to the user or CI agent.
# ------------------------------------------------------------------------------

DOCKER_CONFIG=$(mktemp -d "${TMPDIR:-/tmp}/diaries-docker-config.XXXXXX") \
    || die "Could not create temporary Docker configuration directory."

export DOCKER_CONFIG

cleanup() {
    rm -rf "${DOCKER_CONFIG}"
}

trap cleanup EXIT HUP INT TERM

umask 077

AUTH=$(printf '%s:%s' "${DOCKER_USERNAME}" "${DOCKER_PASSWORD}" \
    | base64 \
    | tr -d '\n')

DOCKER_CONFIG_FILE="${DOCKER_CONFIG}/config.json"

case "${IMAGE_REGISTRY}" in
    docker.io)
        cat > "${DOCKER_CONFIG_FILE}" <<EOF
{
  "auths": {
    "docker.io": {
      "auth": "${AUTH}"
    },
    "https://index.docker.io/v1/": {
      "auth": "${AUTH}"
    }
  }
}
EOF
        ;;
    *)
        cat > "${DOCKER_CONFIG_FILE}" <<EOF
{
  "auths": {
    "${IMAGE_REGISTRY}": {
      "auth": "${AUTH}"
    }
  }
}
EOF
        ;;
esac

[ -s "${DOCKER_CONFIG_FILE}" ] \
    || die "Could not create temporary Docker authentication configuration."

log "Temporary Docker authentication configured for registry ${IMAGE_REGISTRY}."


# ------------------------------------------------------------------------------
# Build and push the responder image.
#
# The temporary DOCKER_CONFIG exported above is automatically used by BuildKit
# when authenticating to the target registry.
# ------------------------------------------------------------------------------

BUILD_DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ)

buildctl-daemonless.sh build \
    --frontend dockerfile.v0 \
    --local context="${SUBPROJECT_DIR}" \
    --local dockerfile="${DOCKERFILE_DIR}" \
    --opt build-arg:REPOSITORY="${REPOSITORY}" \
    --opt build-arg:VERSION="${VERSION}" \
    --opt build-arg:BUILD_DATE="${BUILD_DATE}" \
    --opt build-arg:VCS_REF="${GIT_COMMIT:-unknown}" \
    --output "type=image,\"name=${NAMES}\",push=true"


# ------------------------------------------------------------------------------
# Write image information for later pipeline stages.
# ------------------------------------------------------------------------------

mkdir -p "${BUILD_DIR}" \
    || die "Could not create build directory: ${BUILD_DIR}"

cat > "${IMAGE_INFO_FILE}" <<EOF
IMAGE_REPO="${IMAGE_REPO}"
IMAGE_TAG="${IMAGE_TAG}"
IMAGE="${IMAGE_REPO}:${IMAGE_TAG}"
EOF

[ -s "${IMAGE_INFO_FILE}" ] \
    || die "Could not write image information file: ${IMAGE_INFO_FILE}"

log "imageinfo:"
cat "${IMAGE_INFO_FILE}"
